### ISSUE TITLE
Count of signs is incorrect

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#524] opened 2019-01-09 12:57 UTC
In Global Signbank (not ASL), the number of total signs in the search results is one higher than what I get with "Show all signs". First noticed for International, also see it for Shanghainese now.

**Comment by susanodd** [comment] 2019-01-10 15:03
It used to be counting morphemes as well as signs.
It also seems to check whether the signs are visible / published. Both of those affect the count.
There was some problem with the efficiency of counts when morphemes had to be glossed over.
Some time ago, I tried to revise the code regarding morphemes. That is probably what is wrong.
(Because of the fact that the Dataset is now inside of Lemma rather than Gloss, there ends up being more joins. Also for "subtracting" morphemes from the result. If DEBUG is turned on, you can see it's doing an absurd of queries.)
Maybe @Woseseltops or @vanlummelhuizen can check this?

**Comment by Woseseltops** [comment] 2019-01-11 12:45
Not 100% sure what you mean, @ocrasborn . Are you referring to the weird: '2247 out of 2246' line on the gloss list view you get for Shanghainese? A similar off by 1 error happens for NGT, but not for any of the other datasets.

**Comment by susanodd** [comment] 2019-01-11 15:20
It looks like something might be messed up with the Gloss table versus the LemmaIdgloss table.
If you do a count on the raw database table LemmaIdgloss, where Dataset ID is that of Shanghainese,
you get a different count than when you do a Join query on Gloss x LemmaIdgloss where Lemma.Dataset is Shanghainese. (There is one fewer in the Join than in the LemmaIdgloss table.)

**Comment by susanodd** [comment] 2019-01-14 10:23
I found the line of code that is causing the discrepancy.
In the DatasetListView, the count of the number of glosses is done by an annotation:

`qs = qs.annotate(Count('lemmaidgloss__gloss')).order_by('name')
`
Whereas in GlossListView, either of these is done, depending on whether signs are included:

`context['glosscount'] = Gloss.none_morpheme_objects().filter(lemma__dataset__in=selected_datasets).count()
`
`else:`
`            context['glosscount'] = Gloss.objects.filter(lemma__dataset__in=selected_datasets).count()`

It looks like something is wrong in the database. But I can't find any suspect records.

**Comment by susanodd** [comment] 2019-01-14 12:15
I found something else that may be causing this.
When pagination is used, it looks like the (Django) count retrieved via the paginator does not match.

**Comment by susanodd** [comment] 2019-01-14 13:40
Thanks to @vanlummelhuizen this has been partly repaired. The count of NGT is now the same. The count of the results for Shanghainese still differs by one.

**Comment by susanodd** [comment] 2019-01-16 14:19
I found the problem!!!!
This is related to Issue #297, the sort order.
Try this simple exercise with only Shanghainese selected.
Do a Search on Gloss (English) "Chair".
You get a list of FIVE results. (see screenshots below)
It shows up with the default sort of Lemma ID Gloss.
Then if you click on the Annotation ID Gloss (English) column to sort it by that instead, the results are displayed again, but now there are only FOUR results!!!
Something happens in the order_queryset_by_sort_order method.

![sorted-by-lemmaidgloss](https://user-images.githubusercontent.com/24272544/51254544-9e6ec780-19a1-11e9-9541-2782d87b47ed.png)

![sorted-by-annotation-idgloss-english](https://user-images.githubusercontent.com/24272544/51254566-a3cc1200-19a1-11e9-8e6a-e1e2f369c76e.png)

**Comment by Woseseltops** [comment] 2019-01-18 10:49
Good find @susanodd . Rephrasing of the problem: gloss 5547 'chairman' shows up twice in the search results, but you can make it go away by sorting.

**Comment by Woseseltops** [comment] 2019-01-18 13:18
Spent some time together with @susanodd trying to figure out what's happening here. Turns out right at the end of filtering the search results based on all kinds of criteria, the remaining glosses are being sorted. During sorting the groups of remaining glosses is split into two subgroups:

```python
        qs_letters = qs.filter(**{sOrder+'__regex':r'^[a-zA-Z]'})
        qs_special = qs.filter(**{sOrder+'__regex':r'^[^a-zA-Z]'})
```

It's split by a regex, based on whether the field that's being sorted on starts with a special char or not. These two groups are then sorted separately and then added together again, so the special characters are always at the end:

```python
        ordered = list(qs_letters.order_by(sort_key))
        ordered += list(qs_special.order_by(sort_key))
```

Problem is that when you sort on lemma (which I think is the default?), and there are multiple lemma translations, it tries all of them. The gloss chairman had the English translation 'chairman', which matches the first regex, and the Chinese translation '-', which matches the second. This means 'chairman' was in both groups, and when these two groups were added together, 'chairman' was in the list twice. 

So now we know the cause, but not the solution yet. What should happen when sort the list on lemma, and there are multiple for a gloss? Only pick the first language?

**Comment by Woseseltops** [comment] 2019-01-18 13:36
> Or does this not address your question fully?

Haha no not really. The question is: what do we do if we want to sort on lemma, but for a gloss there are actually lemmas (like one for English and one for Chinese)... do we sort on the English or the Chinese one? 

This was the case for 'Chairman', like you can see in Susan's screenshots above.

**Comment by ocrasborn** [comment] 2019-01-18 13:39
Err... but then if the default sort would be on annotation ID gloss, and if a user decides to change that to lemma gloss, then they have to choose which column header to click on to initiate the re-sort, no? They either click on Lemma (English) or on Lemma (Chinese). In the last screenshot above, I only see a single Lemma ID Gloss column, but we should have as many as we have translation languages, each with their own column header. Is this a to-do that we hadn't identified yet, to add the multilingual lemma glosses to the list view?

**Comment by vanlummelhuizen** [comment] 2019-01-21 13:21
I made multiple LemmaIdgloss columns in #528. This also solves the last count problem as far as I can see. Happy, @ocrasborn ?

**Comment by susanodd** [comment] 2019-01-28 13:58
This seems to still be broken.
If you have NGT selected and then Select All Signs, it now shows even more signs found.

Number of matches: 4069 out of 4058. Datasets: NGT.

**Comment by susanodd** [comment] 2019-01-30 14:51
Okay, the above change done by @vanlummelhuizen looks like the default sort was still left as lemmaidglosstranslation, so the error did not get resolved.
If you look at the Dataset Detail view, it looks like the languages mentioned (Dutch for NGT and Chinese for Shanghainese) are the "first" language in the Languages field, although Chinese is not specified as a Default language for the Shanghainese.

Question: What to do about default sorting order if more than one Dataset is being shown?

**Comment by susanodd** [comment] 2019-01-31 16:06
@vanlummelhuizen and @susanodd spent lots of time on resolving this issue. The default sort order is now Annotation ID Gloss of the default keywords language setting. The special characters are after the alphabetic characters. That had been causing the count to go wrong before, because when translations for more than one language overlapped, the gloss was being counted twice. That has been solved by restricting it to the keywords default language.

**Comment by susanodd** [comment] 2019-02-08 14:50
@Woseseltops and @susanodd debugged one of the tests that was failing.
There were empty annotationidgloss translations for the testing glosses and that caused the test glosses to disappear from the search results.
This has been fixed in the code. This may or may not solve any other issues.

**Closed** 2019-02-14 17:23 UTC
Labels: bug, high priority
