### ISSUE TITLE
Cannot add a compound part

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#868] opened 2022-12-15 14:09 UTC
Under the Morphology panel, when trying to add a compound part, all goes well until the 'Add Component' button: that leads to the following error message. "The requested page was not found on the server."

**Comment by vanlummelhuizen** [comment] 2022-12-15 16:04
I have pinpointed the problem to this change:

```diff
commit 72e3bd10805fc0610e9aab71ade09e10529674cf
Author: susanodd <mijnoog@kpnmail.nl>
Date:   Tue Oct 18 15:43:55 2022 +0200

    Issue #658: Fixed morphemes, notes, query parameters.
    
    Fixed choice lists in dictionary forms and get_queryset where used.

diff --git a/signbank/dictionary/forms.py b/signbank/dictionary/forms.py
--- a/signbank/dictionary/forms.py
+++ b/signbank/dictionary/forms.py
@@ -538,12 +551,21 @@
 class GlossMorphologyForm(forms.ModelForm):
     """Morphology specification of a Gloss"""
 
     parent_gloss_id = forms.CharField(label=_(u'Parent Gloss'))
-    role = forms.ChoiceField(label=_(u'Type'),choices=get_morphology_type_choices,
-                             widget=forms.Select(attrs=ATTRS_FOR_FORMS), required=True)
+    # role = forms.ChoiceField(label=_(u'Type'),choices=get_morphology_type_choices,
+    #                          widget=forms.Select(attrs=ATTRS_FOR_FORMS), required=True)
     morpheme_id = forms.CharField(label=_(u'Morpheme'))
 
     class Meta:
         model = MorphologyDefinition
         fields = []
 
+    def __init__(self, *args, **kwargs):
+        super(GlossMorphologyForm, self).__init__(*args, **kwargs)
+        self.fields['role'] = forms.ChoiceField(label=_(u'Type'),
+                                                choices= choicelist_queryset_to_translated_dict(
+                                                    list(FieldChoice.objects.filter(field='MorphologyType').order_by(
+                                                        'machine_value')),
+                                                    ordered=False, id_prefix='', shortlist=False
+                                                ),
+                                                widget=forms.Select(attrs=ATTRS_FOR_FORMS), required=True)
```

but I have yet to solve it. @susanodd feel free to chip in.

**Comment by susanodd** [comment] 2022-12-15 16:39
Yes @vanlummelhuizen that is exactly where the problem is. It look me more time to locate it because the code redirects and doesn't give any helpful information.
It seems it's the wrong type. On the example I tried, it had 2 instead of a component field choice.
Perhaps it needs to be a queryset.

**Comment by vanlummelhuizen** [comment] 2022-12-19 11:28
I found a solution, making the code be bit more readable in the process.

**Comment by vanlummelhuizen** [comment] 2022-12-19 11:41
My changes: https://github.com/Signbank/Global-signbank/commit/795e605fa3045f36c976d98159f82d5050d83f67

**Comment by vanlummelhuizen** [comment] 2022-12-19 11:49
This is live now. @susanodd @ocrasborn I am closing this issue. If you find it is not solved, we can reopen it again.

**Closed by vanlummelhuizen** 2022-12-19 11:49 UTC
Labels: bug, high priority, morphology
