### ISSUE TITLE
Improve developer experience with CNGT_scripts

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#803] opened 2022-04-21 10:25 UTC
The external CNGT_scripts dependency is inconvenient during installation, and confusing to new people trying to install Signbank. I believe the advantages of having some code in another location do not justify these downsides.

**Comment by vanlummelhuizen** [comment] 2022-04-21 13:18
The problem is not that CNGT_scripts is external. You can easily pip install from git repos. The problem is that that repo is not properly set up (as Python package). You can blame me for that. 

I guess we have two choices:

1. Forget about CNGT_scripts and copy exactly what we need to the Signbank repo.
2. Properly set up CNGT_scripts as a Python package and pip install in Signbank.

We could also implement a hybrid solution: first do 1 for the time being, and than take some time to do 2.

**Comment by Woseseltops** [comment] 2022-04-21 14:18
Changed the title to reflect your viewpoint as well @vanlummelhuizen :) . It also made me think of a third approach, which probably is easiest to realize, which is to simply add the Github repo to the requirements.txt file: https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

**Comment by vanlummelhuizen** [comment] 2022-04-25 07:14
@Woseseltops Looks exactly what we need!

**Comment by Woseseltops** [comment] 2022-04-29 11:06
Added it, untested yet

**Comment by Woseseltops** [comment] 2022-05-20 10:56
For completeness, in the latest deploy I noticed this gave an error, still need to investigate

**Comment by susanodd** [comment] 2022-06-02 05:27
It still gives an error.

**Comment by susanodd** [comment] 2022-06-02 09:55
This is the text in the deploy log about the scripts:

`ERROR: File "setup.py" not found for legacy project CNGT-scripts from git+https://github.com/vanlummelhuizen/CNGT-scripts@master#egg=CNGT-scripts (from -r /var/www/repo/requirements.txt (line 17)).`

That seems to be the only thing.

**Comment by vanlummelhuizen** [comment] 2022-06-15 11:17
@Woseseltops As I also emailed you, I have turned the CNGT-scripts repo into a Python package: https://github.com/vanlummelhuizen/CNGT-scripts/tree/packaging. It could be installed in a Signbank instance with `pip install git+https://github.com/vanlummelhuizen/CNGT-scripts@packaging#egg=CNGT_scripts` (and change it in `requirements.txt`). Any restrictions on when to do this?

**Comment by susanodd** [comment] 2022-06-15 15:32
Great, @vanlummelhuizen !

**Comment by vanlummelhuizen** [comment] 2022-06-20 11:21
Just put this thing live. Seems to work. Closing this now.

**Closed by vanlummelhuizen** 2022-06-20 11:21 UTC
Labels: enhancement
