### ISSUE TITLE
OtherMedia with weird characters in the filename won't download

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#440] opened 2018-03-09 09:19 UTC
You get an empty file instead. 

Discovered by Merel.

(cc @ocrasborn )

**Comment by ocrasborn** [comment] 2018-03-09 10:30
maybe rather "non-alphabetic characters"? ;-)

**Comment by susanodd** [comment] 2018-03-12 13:05
signbank.science.ru.nl//dictionary/gloss/6535/
That one has Chinese characters in the filename of the first Other Media, and gives an error (file not found).
The second Other Media gives fetched garbage in the webpage.

**Comment by susanodd** [comment] 2018-03-12 13:14
signbank.science.ru.nl//dictionary/gloss/3117/
That one has twenty or so (more like 37) Other Media files of all different sorts.
The Other Media is not found on the server.

**Comment by susanodd** [comment] 2018-03-12 13:15
This one actually works, and the Other Media is found on the server:
signbank.science.ru.nl//dictionary/gloss/796/

**Comment by susanodd** [comment] 2018-03-12 13:18
This one works too!
signbank.science.ru.nl//dictionary/gloss/796/

**Comment by susanodd** [comment] 2018-03-12 13:25
I looked in the database to find the above examples.
The suspicious characters were the Chinese symbols.
And the other ones that didn't work have path names with prefix https:// stored in the database.
A few of the filenames have "_knippen nodig" before the extension.

**Comment by vanlummelhuizen** [comment] 2019-01-21 13:46
For a HTTP requests for a video with Chinese symbols in it, those symbols are encoded using [percent encoding](https://en.wikipedia.org/wiki/Percent-encoding). I will try what happens if we decode the url back to the reail chinese symbols.

**Comment by susanodd** [comment] 2020-08-31 13:29
Is anybody working on this issue? There may be a similar problem with uploads.
While working on Issue #678, I am doing searches from the Menu bar with all datasets.
For that issue, there are problems because many languages have empty Annotations for other languages.
This messes up the default sorting.

Regarding this issue:
I noticed there is now a dataset ZEI with Farsi.
This is causing errors because of the characters.
It seems to be using the percent encoding. But that doesn't seem to be used in other code.
(e.g., when a video or image path is created and this is looked for on disc. On my local computer this has slashes in it instead of percent signs.)

**Comment by susanodd** [comment] 2020-09-01 10:47
For dataset ZEI, the default language is set to Farsi.
This results in image and video filenames with special characters.
@ocrasborn it's your dataset. Would you care if the English is used for the files?

**Comment by susanodd** [comment] 2020-09-01 10:51
On my local server, this causes problems:

<FieldFile: glossvideo/ZEI/می/میوه-A-37124.mp4>

**Comment by ocrasborn** [comment] 2020-09-01 17:42
@susanodd : no, for the Farsi dataset, filenames in English would be fine. Not sure we would want to impose this on all datasets though, if not needed.

**Comment by vanlummelhuizen** [comment] 2020-09-02 07:07
@susanodd @ocrasborn using English for file names is no guarantee that these problems will go away, because also English annotations may technically contain Farsi or other non-ASCII characters. 

There is a setting called ESCAPE_UPLOADED_VIDEO_FILE_PATH which makes video file path escape special characters with percent encoding if set to True. Perhaps that helps.

**Comment by susanodd** [comment] 2020-09-02 10:06
That didn't help.

**Comment by susanodd** [comment] 2020-09-02 10:08
I tried converted back using ord on the characters to see what's going on.
I suspect there might be some filenames already stored in the database that are in the wrong encoding.

**Comment by susanodd** [comment] 2020-09-02 10:11
I noticed there are some glosses that start with "(".
Do we really want subdirectories under the dataset starting with "("?

**Comment by susanodd** [comment] 2020-09-04 12:33
This is in the database when querying video objects (model Video) for the gloss 37124 in dataset ZEI.

<GlossVideo: glossvideo/ZEI/می/میوه-A-37124.mp4.bak11871>

This is probably causing the routines that look at the file extension to sometimes fail.
There's another path in the log with extension mp4.png

**Comment by susanodd** [comment] 2021-03-11 09:42
I finished #699 which generates hyperlinks for glossvideo and glossimage.
It turns out there is are methods in the Gloss model which take care of the special characters.

Maybe OtherMedia should be included in the CSV or another CSV in order to check what is being generated?
It's not exactly what this issue is, but perhaps easier for a human to check?

**Comment by susanodd** [comment] 2021-03-15 13:28
@Woseseltops, @vanlummelhuizen, @ocrasborn Could it be that it's not possible to delete OtherMedia files?

Yes, it's possible to delete OtherMedia objects in Gloss Detail Edit, but there is no code that actually deletes the files.

**Comment by susanodd** [comment] 2021-03-15 13:35
Regarding this issue, I discovered a mismatch with the "source" filename that you try to upload and the "destination" filename it wants to create.
It looks like the issue is correct, that "something" is being done, but the file wasn't actually uploaded if there were special characters.
The path wasn't being constructed correctly, but an OtherMedia object (containing the new filename) was being created, and the destination file was empty.

I can't say why this is. I fixed this on my machine. Now the uploaded file has the correct filename and the OtherMedia object matches this and the new file has contents.
Except, when you want to delete the other media, it does not delete the file. (Regardless of whether it matches or not, there is no code that even tries to do this.)

**Comment by susanodd** [comment] 2021-03-15 13:38
So the issue description is that the file is empty, not that it downloads empty; It uploads empty.

**Comment by susanodd** [comment] 2021-03-16 12:22
This is kind of related to the interface languages.

When the user uploads "other media" the file that is uploaded retains its filename and is put in a gloss number folder in othermedia.

This is related to this issue because the source filename can have special characters in it and it gets copied.
But it can also be a right to left language filename.

I checked this out for glossvideo and glossimage. The filenames are all percent coded now on the server.

At present this is not done for other media.

**Comment by susanodd** [comment] 2021-03-18 10:31
I kind of fixed this.
I found out what was causing the problem during upload, the original filename of the file on the user's computer was being put into the new OtherMedia object. So if there were weird characters in that, they were being copied, along with the original extension.

I worked step by step through the uploading. The Django upload knows the real type of the file it is uploading, even if it does not match the extension. There was something weird with "m4v" extensions, but during upload, Django recognises that this is an mp4 file. So now based on the actual type of the file Django is uploading, I made the new file have the 'mp4' extension, so it will be recognised when the user accesses it. But this also had to be changed in the path save in the OtherMedia object, because it was the original path.

Hopefully @vanlummelhuizen and @Woseseltops are okay with this.

I have several exceptions in the upload other media code now, so if something is messed up it won't do anything.

However, deleting an OtherMedia from a Gloss only deletes the OtherMedia object, not the actual file.
That was also causing problems because of any weird characters.

So probably something similar to what is done for videos is needed?
@ocrasborn ?

**Comment by susanodd** [comment] 2021-03-18 10:57
I'm looking at the OtherMedia objects in the database to see what mysterious paths exist.
Here is a gloss with numerous other media objects, most of which have no type showing:
https://signbank.cls.ru.nl/dictionary/gloss/3117/
It looks like it's a test gloss.
Do we want all of these file extensions to be recognised and receive a file type in the list?

![other-media-filetypes](https://user-images.githubusercontent.com/24272544/111615491-1a166a00-87e1-11eb-8cb4-fa0b26346aaa.png)

**Comment by susanodd** [comment] 2021-03-18 11:01
Here is the same gloss on my local server showing the repairs:

![other-media-types-theoddbranch](https://user-images.githubusercontent.com/24272544/111615977-a2950a80-87e1-11eb-8ee4-50b61e7e487b.png)

**Comment by susanodd** [comment] 2021-03-18 11:12
Please note, I do not have these files on my local computer! Those filenames are obtained from the file names stored in the paths in the OtherMedia objects. The None file types are where the extension is unknown. One of those has an extension ".do".

**Comment by susanodd** [comment] 2021-03-18 14:33
I've added some extra functionality for displaying the list of OtherMedia.
When loading the Gloss Detail View, if an OtherMedia has a bad pathname, the Download is greyed out and disabled.
Also, if the OtherMedia is accidently in the othermedia (parent) folder, instead of the gloss's folder (othermedia/gloss_id), it is also disabled. Such a location is legacy code.
I decided to display the links but make them disfunctional. That way, somebody editing the gloss has the change to delete them.
The code displays messages to the log about such messed up OtherMedia objects.

![othermedia-paths-disabled](https://user-images.githubusercontent.com/24272544/111643079-f2ce9580-87fe-11eb-8406-6b370089b9a4.png)

**Comment by susanodd** [comment] 2021-03-23 11:08
@Woseseltops @vanlummelhuizen can I get some feedback before pushing the solution I'm working on?

I have modified functionality as follows:

1. update.py -> add_othermedia

- this now has a reverse_url to return to either the GlossDetail or MorphemeDetail view
- the code now checks the content_type of the file during upload to change the file extensin "m4v" to "mp4" (if this applies). That file extension is not recognised by python mimetypes. But Django recognises the source file as being mp4.
- if necessary, the new filename is quoted
- the path stored in the OtherMedia object matches the new uploaded file
- error messages are generated if there was a problem uploading


2. models.py -> OtherMedia -> get_othermedia_path

- this method returns a tuple (media_okay, path, other_media_filename)
- it checks whether the path stored inside the OtherMedia object is a legacy location

3. adminviews.py -> context['other_media'] in GlossDetailView and MorphemeDetailView

- this uses the new get_othermedia_path method
- passes the new media_okay flag to the views as well as the file_type based on python mimetypes

4. gloss_detail and morpheme_detail

- if media_okay is false, the Download is greyed out and disabled
- error messages appear for the user if there was a problem uploading

**Comment by susanodd** [comment] 2021-03-23 11:12
Question 1: what is the best place for (2) ? I put it in the model because there are similar methods for getting video and image file paths.

Question 2: I would like to add an existence check on the file in writable inside the get_othermedia_path and make media_okay be false if the file does not exist. Then these could also be disabled in the Detail views.

Question 3: What to do about deletion? The actual files are not deleted when an OtherMedia is deleted in the Detail Edit views.

**Comment by susanodd** [comment] 2021-03-23 11:26
@ocrasborn:

Question 4: What types of Other Media should there be?

I modified the input to accept: video/* and image/*
(In the current database, users have also uploaded txt, pdf, csv, and py.)

**Comment by vanlummelhuizen** [comment] 2021-03-24 14:32
> Question 1: what is the best place for (2) ? I put it in the model because there are similar methods for getting video and image file paths.

Seems like the best place to me.

> 
> Question 2: I would like to add an existence check on the file in writable inside the get_othermedia_path and make media_okay be false if the file does not exist. Then these could also be disabled in the Detail views.

I think that is a good idea. Please do that.
> 
> Question 3: What to do about deletion? The actual files are not deleted when an OtherMedia is deleted in the Detail Edit views.

I think deleting an OtherMedia object should also delete the file on disk or at least move it to a 'deleted' folder of some sort. @ocrasborn what do you want to happen to deleted OtherMedia files?

**Comment by Woseseltops** [comment] 2021-03-25 08:55
Hi @susanodd , some responses from my side:

> Hopefully @vanlummelhuizen and @Woseseltops are okay with this.

From your description these all seem good fixes, making the whole OtherMedia functionality a lot more robust.

> can I get some feedback before pushing the solution I'm working on?

Perhaps this was something you were already working on before we decided to change our workflow, but just as a quick reminder of our new workflow :)
* You push whatever you think is good to a separate feature specific branch
* You request feedback in the form of a pull request and choose an appropriate reviewer (or both, if it's a big thing)
* Once you get the agreement, we merge the branch into master

> Question 3: What to do about deletion? The actual files are not deleted when an OtherMedia is deleted in the Detail Edit views.

I think this deserves a separate issue ;) .

> Question 4: What types of Other Media should there be?

I'd say what is currently in the database is the best predictor of what there will be in the future as well

**Comment by susanodd** [comment] 2021-03-25 09:41
@Woseseltops, yes, I understand the new workflow.
Although I am still working from theoddbranch because it's much newer code. Some changes on theoddbranch that are not yet on the master are from the end of january.
I will create a new branch for the other media after theoddbranch has been merged into the master.
Although I'm quite fond of theoddbranch name.

**Comment by susanodd** [comment] 2021-03-31 09:38
@Woseseltops, the other media currently in the database is predominantly .mp4, .mov, .png, .jjpg
The .txt, .csv, .pdf, .py are in test signs.
One of the uploaded images is a screenshot of an error message.

**Comment by susanodd** [comment] 2021-04-01 10:23
Changes to fix the problems related to this issue are on an issue branch other_media_branch for #735.
This has been pushed to github.

**Closed** 2021-04-15 13:34 UTC
Labels: bug
