### ISSUE TITLE
Harmonise display of boolean field values

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#367] opened 2017-08-17 11:16 UTC
* After the boolean fields repeated movement / alternating movement have been filled and the page is reloaded, the values appear as yes/no. During editing and saving, however, they appear as "true" (or --------). If it's not too difficult, please change the "true" to "yes".
* See also #38 , perhaps

**Comment by susanodd** [comment] 2017-08-22 10:01
This has to do with actual "True" and "False" values for the Checked Box, versus the display of a value. When a value is True in the database, then the Checkbox needs to be a True value in order to be Checked. (This is in the javascript.) Otherwise, the case when the Checkbox should be "already checked" (because it's True in the database) doesn't work properly.
I'll see if I can fix how this is displaying. This also happens for Dutch. ('Ja' versus 'True'.)

**Comment by susanodd** [comment] 2017-08-22 11:21
Okay, I have changed it to be Yes, No.
But... the problem is that this doesn't work for Dutch, etc.. It's not Ja, Nee.
This has to do with the way translation is done. (The {% trans Yes %} {% trans No %} blocks.)
For all the other fields, the translation is inside the FieldChoice table. So these can be retrieved by the database when returning the value. But this information is not available for Yes, No. (The repeat, altern phonology fields.)
To fix this, there can be a FieldChoice for the repeat and altern fields (Boolean choices) in the database, which is basically the alternative languages. But then still use the Checkbox rather than a pulldown (of e.g., Yes, No) for display.
This kind of solution would allow the translation of the (Boolean) values to be moved into the database rather than in the "trans" messages code. The "trans" code is only called at page generation. But since the Detail View relies on repeated editing, the "trans" code doesn't get called again until the user reloads the page. The javascript can't call the "trans" code.

I'll see if I can do something with saving temporary variables.
But..... that would need to be hardcoded translated values for Yes and No in the code.

(Since the python / django code can only either access context variables or fetch stuff from the database, but not the "trans" translations. The translation has to be either in the database, or else hardcoded in variables.)

**Comment by susanodd** [comment] 2017-08-23 12:32
Okay, I fixed this.
It turns out, there is a line of code in update.py where the actual Language value of Yes is being used to determine if it's True or False. So I added the values 'ja', 'Ja', and the Chinese value '是' to this code.

**Comment by susanodd** [comment] 2017-08-25 13:13
This is fixed now and is on github, master branch.
I came across the code that needed to be changed while working on the Handshape Hyperlinks.
The updates are all part of one commit. (Sorry Wessel!)
I put comments in the code to point the changes out.

**Comment by vanlummelhuizen** [comment] 2019-10-31 08:03
@ocrasborn @susanodd Are you happy with this?

**Comment by susanodd** [comment] 2019-10-31 12:44
Checked.

**Comment by susanodd** [comment] 2019-10-31 14:50
I checked that Booleans are displayed correctly in Minimal Pairs. And in the Edit View for Gloss.

**Comment by ocrasborn** [comment] 2019-11-12 15:31
Thanks @susanodd ! Can this be closed now?

**Closed** 2019-11-13 10:14 UTC
Labels: enhancement
