### ISSUE TITLE
Problem when playing an uploaded video

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#886] opened 2023-02-16 15:42 UTC
An error occurs in the drag and drop code, or the form that it uses, when opening a gloss detail page
See: https://signbank.cls.ru.nl/dictionary/gloss/44008/

Might be a browser problem, or maybe it is saved somewhere different than in my local setup, or it is something else. 

Check why "id_videofile" is nowhere as 'id' but is only used for 'for'?

**Comment by susanodd** [comment] 2023-02-20 10:20
It won't play in Safari either. It doesn't show the normal image for not available.

**Comment by Jetske** [comment] 2023-02-20 10:51
No, I think that's because the video should be there (it also shows up in the writable/glossvideo/NGT/LO folder) but somehow it still can't find the video. This happens for both LOPEND-VOORTBEWEGEN-B and LOPEN-L, which are both only shown when logged in. Could that be related? 

When I try to upload the same video for those two glosses locally, it works fine.

**Comment by susanodd** [comment] 2023-02-20 11:28
Is the group or permissions messed up?
I get the same on Firefox. But it finds the image for the gloss okay, so the path ought to be correct.

I tried searching on (Dutch annotation) ^LO
and there are 31 results. But in the console, only the matches for 44010 and 44008 show errors. (There are 3 messages about each.)

**Comment by Jetske** [comment] 2023-02-20 11:44
Maybe? But if I (locally) give a test user only permission for "dictionary | gloss | Can Search/View Full Gloss Details" then it finds the corresponding videos for those glosses without problems. 

By the way, I did solve the error for 'onchange' in drag_drop_files.js, that was about the input field 'id_videofile' and presumably not related to the video loading problem.

**Comment by susanodd** [comment] 2023-02-20 12:32
I adjusted the permissions on the server, so they're visible now.

**Comment by susanodd** [comment] 2023-02-22 09:39
I'm trying this now locally on master branch.
I can successfully upload a video (using the normal button not drag and drop).
It successfully shows up.
However, the new video created has the "lemma" of the gloss, not the annotation in its filename.

`writable/glossvideo/tstMH/MA/MAAL-42088.mp4`

(This will be a problem for the variant names.)
(See the fields below. It chose the Dutch Lemma as the filename.)

![add-video-to-gloss](https://user-images.githubusercontent.com/24272544/220581062-ae54ad9e-c5f5-45e6-a08b-09390396f549.png)

**Comment by susanodd** [comment] 2023-02-22 09:42
I have the current global database now.
(I am the owner of the uploaded file, so it shows up on PyCharm runserver.)
I'll try your branch again @Jetske

**Comment by susanodd** [comment] 2023-02-22 11:23
That the new video is stored under a filename that uses the lemma rather than the annotation, this might be relevant

#394 

(There was once a problem with videos disappearing when the lemma was changed.)

**Comment by susanodd** [comment] 2023-02-22 11:30
The most important part of the video filename is the gloss id. The other media is stored underneath a folder for the gloss id. That the video files are stored under a folder of the first two characters of the (lemma) under the dataset. So if you change the lemma, the video file would move to a new folder.

**Comment by Jetske** [comment] 2023-02-23 13:16
instance.gloss.idgloss gives a lemma, but there are different translations for that
instance.gloss.get_annotationidglosstranslation_texts() gives e.g. {'en': 'ACROBATICS-B', 'zh': '杂技-B'}
Are those always valid to put in the file names, and which one to pick?

**Comment by susanodd** [comment] 2023-02-24 11:40
This is still broken.
Lianne asked on Wednesday if it had to do with Apple. I thought at the time, she meant viewing on an Apple computer.
But now I suspect it has to do with Apple recorded videos.

I tried uploading a really old Signbank video from 2016 for the sign GEK-A.
This uploads without any problems.
Although no small video is made. But the video shows up in Detail View.

**Comment by susanodd** [comment] 2023-02-24 13:51
@Jetske @Woseseltops thought it could be that because the video is very large, that it times out during uploading and doesn't finish.

**Comment by susanodd** [comment] 2023-02-24 14:04
I repaired the OtherMedia of Gloss Detail. (There was a Field Choice error!!! #658)
Now it's possible to upload videos via Other Media.
I tried one of the problem files that I had downloaded to my own computer. (One that the permissions were fixed on)
It's a very large file 4.3 MB. It did not work to upload it!!!
I then tried one of the normal test video files (1,8 MB) and that uploads, no problem.
The problem is, the video is actually sucessfully uploaded under othermedia/<id>
And has the correct permissions.
BUT an error was generated during uploading, so it didn't get stored that it was uploaded.

**Comment by susanodd** [comment] 2023-02-24 14:51
I miss apache on my computer!

**Comment by susanodd** [comment] 2023-02-24 14:56
What was confusing (to me) was that because the upload (of the large file) had in fact worked, but it did not show up under Other Media. So when I tried to upload it again, it failed because the file already exists.

I modified the code to create the object before it starts copying the file.
Then if that fails, it deletes the object, etc.

**Comment by susanodd** [comment] 2023-02-24 15:01
The uploading of a large video for Other Media is a success!

**Comment by susanodd** [comment] 2023-02-24 15:05
@Woseseltops was right, the form processing/database connection expired before the uploading was completed.
Now to fix this for uploading videos.

**Comment by susanodd** [comment] 2023-02-24 15:32
I'm examining the videos Lianne uploaded yesterday.
After uploading @Jetske fix:
`-rwxrwx--- 1 ubuntu www-data          3956505 Feb 24 09:39 IN-G-44079.mp4`
This large video has the correct permissions and is VISIBLE!!
However the group is not `signbank-writable`.
The `www-data` group is perhaps the effect of not finishing.

**Comment by susanodd** [comment] 2023-02-24 15:59
I think I repaired all of the non-visible ones.

**Comment by susanodd** [comment] 2023-03-03 16:43
I finally got the Admin working so that it's possible to filter on the file system group.
So far, it's only local. The groups are in a setting.
Next up, to filter on whether the file exists, and on the version.

![local-admin-filter-gloss-video-on-group](https://user-images.githubusercontent.com/24272544/222777246-48124209-5603-449f-8835-afebe2f225b6.png)

**Comment by susanodd** [comment] 2023-03-06 13:52
@Jetske totally weird.
I just tried uploading the downloaded (not viewable on Firefox video from the fietstas) via the Other Media.
I have a print statement to inspect what Python Magic File Type determines.
It's this:
`video/x-matroska`

**Comment by Jetske** [comment] 2023-03-06 14:13
Then it's probably confused by the type. This is set for recording the webcam stream:
options = {mimeType:'video/webm;codecs:vp9'}
And then later on it's changed to mp4..

I'll try some other types

**Comment by susanodd** [comment] 2023-03-08 12:16
Note: Make sure to reload the javascript.....

The webcam videos (also the one I made on FireFox) are not visible on Apple MacOS.

**Comment by susanodd** [comment] 2023-03-08 13:36
@Jetske is it possible something is being displayed "on top of" the video?

It shows correctly for a brief moment when the page is loaded, but then the picture of the "crossed out black screen" shows instead of the video.

In the code (in Safari) there is a huge "other thing" in a container right below the video container. (like a sibling)
mediacontrols-container (I copy pasted it from the browser element below)

`<div class="media-controls inline mac uses-ltr-user-interface-layout-direction" style="width: 450px; height: 259px;"><div class="placard" style="width: 450px; height: 259px;"><div class="container"><button class="bar" aria-label="Ongeldig" disabled="" style="width: 49px; height: 37px;"><picture style="width: 49px; height: 37px; mask-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADEAAAAlCAYAAADr2wGRAAACQklEQVR4Ac3ZA4xcURTG8dq27agTbtgNi6i2jaAIiri2bbtxtuGGtW3bdnv7L1Yn9+Ws7pz5kl+c9J7p++47O1MgF5mNt9iLVkiIlMdBnEFPaHkL9993LEcVmKYbXCapiMGXonAerzEGRWCSungkDvUT61EVMg5RLqIdTFIB8/DV8wlPQDGkJRVOkWLZlyZIgROuowPS0gnXlUHM+9IOF5VPuBgm4DWc4P/fNEgRjPMc8jsWoQL+pCrW46cyzHV0gkmqYDm+i0M9x+hMN1JM74u4/QzSOuKQ55Cs9sV/+9WESTrhBpxwAE0y9WUS3ivDvMcUlETcUxJTPIf8jGkogz+pmc2+3EUvFERcMhiFMh1yI36JQz3CYBTMYV8OIwnB43BK9CAJh6EdqivuKoP8wqbQfXGZ7EM9/ElB9MYjz6F2oLZ4FE374oRPogdlMA2flEOZ9sVFeCT6Ug/7Iw7VFWmJ4XC8++IUJ8Q/loxTykuvIHplsy/jgg8hepDWl0IYgeeel94aVMlBX94EHULrSw5W/prY5rm6f2BwsCEUD0U5W0Ss/NfQTl7d8vGzGkKWMycrf0HUgYzREKIvyt8l3zEPFUCMhlB8Eu+NtJX/p7LyWw6hv8yUPUuuOuZDSNfRxrPy34lY+RuZDqFcrfrKL69uwyFy+k1ITWz1vDfuo6HFEDn+TkpZ+UcFHyLAt4MF0Q83cQF14jHEK3lF2ifAc2+QAM+9QfTnPsEjf5/QVwP7qL8UfdWXtMTMXLzBbjSDeX4DUtBytI+SX08AAAAASUVORK5CYII=&quot;);"></picture></button></div></div></div>`

**Comment by susanodd** [comment] 2023-03-08 13:37
Whatever that thing is, it has the same dimensions as the video container and it looks like it's on top of the video.

**Comment by Jetske** [comment] 2023-03-08 14:26
Hm interesting. Images are shown on top of the webcam video input container, but that should not be the case for the playback video. Isn't that just the video controls like the pause button and all that?

Is this only in Safari?

**Comment by vanlummelhuizen** [comment] 2023-03-09 09:52
check whether an uploaded video is MP4. If not, convert to MP4. See https://ottverse.com/how-to-convert-mkv-to-mp4-using-vlc-ffmpeg-handbrake/

**Comment by susanodd** [comment] 2023-03-09 09:59
The upload in other media converts it.

**Comment by Jetske** [comment] 2023-03-09 11:34
The commit above will cause some conflicts, but I think this added function (convert_to_mp4) might fix it, it works locally at least.

**Comment by susanodd** [comment] 2023-03-14 11:10
There is a command now for converting already uploaded videos so they can be displayed.

But this is suffering from problems described in #911 with ffmpeg.

(@ocrasborn  this is relevant to Lianne's newly uploaded videos if you look at Recently Added Signs.)

**Comment by susanodd** [comment] 2023-03-15 10:19
Okay, the (virtual environment on Global) command that converts the **_already uploaded_** videos works again!
(with caveat)

It successfully converts:
`video/x-matroska` (the webcam videos)

But it doesn't work on:
```
video/mpeg
video/quicktime
```

**Comment by susanodd** [comment] 2023-03-15 10:25
Note, already truncated videos are not retrievable, because that was done during upload. (#911 )

If you browse the recently added signs (NGT), the videos are now visible. But, you will notice some were truncated.

**Comment by susanodd** [comment] 2023-03-15 13:19
@ocrasborn I converted circa 160 Other Media videos that weren't visible (they were in quicktime format).
There's a command to do that now in the virtual environment of the server.
See NGT/ PARAPLU  Videos

**Comment by susanodd** [comment] 2023-04-20 12:30
This seems to be working okay now.

**Closed by susanodd** 2023-04-20 12:30 UTC
Labels: high priority
