### ISSUE TITLE
CSV export broken for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#430] opened 2018-02-20 14:12 UTC
Error message: 'Language' object has no attribute 'name_en'

**Comment by vanlummelhuizen** [comment] 2018-02-21 09:30
I changed something to deal with this. Not in the ASL Signbank yet.

**Comment by Woseseltops** [comment] 2018-02-21 13:38
Added the change by @vanlummelhuizen to the ASL branch as well. That fixed this particular problem.

@vanlummelhuizen , I see a similar piece of code further down below at the morpheme list view. Do we want to change it there as well?

Unfortunately, a second problem emerged now: 

```
Wed Feb 21 14:19:30 2018 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 419] during GET /signs/search/?sortOrder=idgloss&search_type=sign&glosssearch_en_US=&keyword=&lemmaGloss=&semField=&id_morpheme=&hasComponentOfType=&hasMorphemeOfType=&handedness=&weakdrop=0&weakprop=0&locPrimLH=&initial_secondary_loc=&final_secondary_loc=&domSF=&domFlex=&oriChAbd=0&oriChFlex=0&subhndsh=&subhndsh_letter=0&subhndsh_number=0&movSh=&wordClass=&wordClass2=&lexCatNotes=&derivHist=&iconType=&relation=&hasRelation=&relationToForeignSign=&hasRelationToForeignSign=0&inWeb=0&isNew=0&definitionRole=&definitionContains=&createdBefore=&createdAfter=&createdBy=&format=CSV&paginate_by=500 (130.132.35.237)
OSError: write error
[pid: 25485|app: 0|req: 10/29] 130.132.35.237 () {62 vars in 2676 bytes} [Wed Feb 21 14:18:23 2018] GET /signs/search/?sortOrder=idgloss&search_type=sign&glosssearch_en_US=&keyword=&lemmaGloss=&semField=&id_morpheme=&hasComponentOfType=&hasMorphemeOfType=&handedness=&weakdrop=0&weakprop=0&locPrimLH=&initial_secondary_loc=&final_secondary_loc=&domSF=&domFlex=&oriChAbd=0&oriChFlex=0&subhndsh=&subhndsh_letter=0&subhndsh_number=0&movSh=&wordClass=&wordClass2=&lexCatNotes=&derivHist=&iconType=&relation=&hasRelation=&relationToForeignSign=&hasRelationToForeignSign=0&inWeb=0&isNew=0&definitionRole=&definitionContains=&createdBefore=&createdAfter=&createdBy=&format=CSV&paginate_by=500 => generated 0 bytes in 67501 msecs (HTTP/1.1 200) 7 headers in 351 bytes (1 switches on core 1)
```

It looks like uwsgi is taking too long to come up with the response, and Apache as a result closed the connection, but I'm not sure. Will investigate this next morning.

**Comment by vanlummelhuizen** [comment] 2018-02-21 15:13
@Woseseltops I also changed the similar piece of code. See 
https://github.com/Signbank/Global-signbank/commit/83dfb6946a252740625e387d94720e77cb3bf1ad

I have no clue about the uwsgi problem.

**Comment by Woseseltops** [comment] 2018-02-22 09:44
So far I have not been able to fix this uwsgi problem. What happens is that the when clicking the CSV button, it loads for some time (building the CSV), and then returns a 500 internal server error. The problem is that connection is lost either between the browser and Apache or between Apache and uwsgi during this CSV build time. 

Things I noticed:
* This is caused by the CSV creation process taking a long time; if you only create a CSV file for a limited set of signs, there is no problem. 
* I can also make the problem (for the ASL Signbank) go away by simply decreasing the amount of work Django has to do, for example by removing these lines:

```
# get languages
signlanguages = [signlanguage.name for signlanguage in gloss.signlanguage.all()]
row.append(", ".join(signlanguages))

# get dialects
dialects = [dialect.name for dialect in gloss.dialect.all()]
row.append(", ".join(dialects))
```
* During the waiting for the CSV to be created, 1 core is at 100%, and it stops as soon as the error message is displayed. Not sure whether it stops because 'pipe was broken' or because it discovers the pipe is broken as soon as the process is ready.
* I just tried for the Global Signbank, and there we have the same problem if we request a CSV for all signs. The only difference is that the load time is significantly longer (because the dataset is larger?). I can't find an error message in the log files for the Global Signbank, though, so not 100% sure it's exactly the same.

For now, I've fixed the problem for ASL by removing the sign language and dialect lookup (hardcoded as an empty list), as these are not set in the ASL Signbank anyway.

**Comment by ocrasborn** [comment] 2018-02-22 09:46
Should we close this issue then, or keep looking for a more profound solution?

**Comment by Woseseltops** [comment] 2018-02-22 09:52
I'd say close this issue and create a separate one for this apparently separate issue: https://github.com/Signbank/Global-signbank/issues/432 .

**Closed by Woseseltops** 2018-02-22 09:52 UTC
Labels: ASL, blocking, bug
