### ISSUE TITLE
Store a revision history: who has changed what on which date?

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#115] opened 2015-12-10 11:46 UTC
- There now only is a last-saved time stamp per record? The wish is to be able to see a true version history, human-readable: a table with who has changed which field to what.
- Make this accessible only to Editors and Publishers.

**Comment by henrinie** [comment] 2015-12-23 15:26
I believe that you might have revision history in the django adminpages.
Try this url: http://signbank.science.ru.nl/admin/dictionary/gloss/47/history/ (change the gloss id if you don't happen to have one with id 47).

I can access revision history in Finnish signbank (in django adminpages) by selecting a gloss and then clicking *history* in top right of the page.

**Comment by Woseseltops** [comment] 2016-02-05 13:31
@henrinie turns out to be correct. This is not standard Django functionality, but done with the app django-reversion (https://django-reversion.readthedocs.org/en/latest/) added by Steve Cassidy. Besides the timezone, which was still Australian and is now set to European, it already works! 

Would this be enough, @ocrasborn ? Because it would mean that only people with access to the Django admin could see it. Judging by the django-revision manual, I could make a panel in the detail view that lists all revisions, but that would of course take some time.

**Comment by ocrasborn** [comment] 2016-02-05 13:50
Yes, that would be OK for now, if it indeed shows the changes in terms of field–old value–new value. Is that somewhere already in the admin now, @Woseseltops ? I will demo it to the ASL team in the first week of March, and then we can always create a nicer interface later on.

**Comment by Woseseltops** [comment] 2016-02-05 14:21
> Is that somewhere already in the admin now

Yes. Go to a random gloss, like http://signbank.science.ru.nl/admin/dictionary/gloss/3117/, and click 'History' in the upper right corner.

> if it indeed shows the changes in terms of field–old value–new value

No; now that I look closer, I see that it's more like a series of snapshots. You see a list of dates that represent change times, and when you click such a date, you are taken to a detail view that shows how the gloss looked before that time. I guess you want something different, then?

**Comment by ocrasborn** [comment] 2016-02-05 14:58
Yes, I think we will need something more user-friendly. I will discuss in March what exactly the demands are; I'll remove the top priority for now.
Question and comment:
* Where does the "Comment" info come from? It's not automatically generated on the basis of the changes, is it? It looks like some sort of log info that you can only enter when doing things in Django admin.
* The button next to "History", "View on site", doesn't work as expected. Please repair when continuing with this issue again later.

**Comment by Woseseltops** [comment] 2016-02-05 15:13
> It's not automatically generated on the basis of the changes, is it? 

I was quite surprised to find it there as well; it must be automatically generated, because I didn't add it manually.

**Comment by richardbank** [comment] 2016-02-05 15:17
I'm sorry I never told the both of you about it...
I'm not fully confident though that all changes are recorded. I use the gloss TESTonnoz on a regular basis, but I would have expected to see more changes than the current 10 (of which 8 today; and Inge's change is actually mine). I'll look at this more often to see if everything is recorded.

**Comment by ocrasborn** [comment] 2019-06-28 07:46
Op https://django-reversion.readthedocs.io/en/release-1.8.1/how-it-works.html vond ik dit:

@vanlummelhuizen wrote to me: Whenever you save changes to a model, it is serialized using the Django serialization framework into a JSON string. This is saved to the database as a reversion.models.Version model. Each Version model is linked to a model instance using a GenericForeignKey.
Als ik in de Signbank-database kijk, lijkt het er inderdaad op dat steeds een oude versie van het hele object opgeslagen wordt.

**Comment by Woseseltops** [comment] 2019-07-04 08:27
I have fixed the gloss page for on the admin; it's super slow, but at least you can see something again. Indeed, in the admin I get a list of previous version of the gloss, along with the user and time. See for example: https://signbank.science.ru.nl/admin/dictionary/gloss/3117/history/ . I guess this is exactly what was needed, right @ocrasborn ?

**Comment by ocrasborn** [comment] 2019-07-04 11:12
- Thanks @Woseseltops , this is indeed part of the puzzle. It looks like every 'edit' button click is logged, even if no changes are made. Could you test if this is indeed the case? Or why else would so many rows be empty in the last column?
- Then, if I click on one, it leads me back to https://signbank.science.ru.nl/admin/dictionary/gloss/. Is that a bug, and should more detail on the actual values (old, new) be available?
- I will discuss with Julie what level of detail she needs, and whether a admin access suffices.

**Comment by Woseseltops** [comment] 2019-07-04 14:38
> It looks like every 'edit' button click is logged, even if no changes are made. Could you test if this is indeed the case? Or why else would so many rows be empty in the last column?

No only real edits are logged. The last column is almost always empty or some text written somehow by a human (I can see in the database it's sometimes also in Dutch). I have no idea where this option to add text to your change has existed and how that would have worked.

> Then, if I click on one, it leads me back to https://signbank.science.ru.nl/admin/dictionary/gloss/. Is that a bug, and should more detail on the actual values (old, new) be available?

Are you sure? Because I'm led back to the detail interface of the gloss as it was during that revision.

**Comment by ocrasborn** [comment] 2019-07-04 19:13
Yes, I'm sure. But: I see i missed the error message that comes with it: "Could not load wesseltest31 version - incompatible version data"

**Comment by henrinie** [comment] 2019-07-06 10:05
The `incompatible version data` could possibly happen if you have done data migrations after the version was saved.

**Comment by vanlummelhuizen** [comment] 2019-07-08 07:10
> The `incompatible version data` could possibly happen if you have done data migrations after the version was saved.

Note that [django-simple-history](https://django-simple-history.readthedocs.io/en/stable/) does not suffer from this problem as it keeps track of versions using a shadow model for each model, and this shadow model gets the changes made to the model it shadows when migrating.

Moving to another versioning system has it's downsides of course.

**Comment by Woseseltops** [comment] 2019-07-10 07:27
Another solution could be to create a simple model GlossChange, which is created each time an edit is done, and stores which gloss, which field, previous value, new value, user and time. This is easy to build, avoids the complicated migrations all together, but you give up the option to (easily) go back to an older version. 

Solution so far:
* Keep reversion. Downside: every time we make a change to the gloss model, you cannot go back to previous versions, while the interface suggests you can.
* Django-simple-history. Downside: yet another dependency that can give problems (for example when installing or upgrading Python/Django).
* Simple Django model to log changes. Downside: you cannot go back to previous versions at all.

**Comment by ocrasborn** [comment] 2019-07-10 07:51
If a new model is simple to make, and creating a page accessible to Dataset Managers alone is also easy to make, then let's just do that, @Woseseltops .

**Comment by Woseseltops** [comment] 2019-07-10 08:14
> creating a page accessible to Dataset Managers 

So an overview of changes to glosses only in a single dataset? No problem for the third solution, and probably also not for the second solution (based on a a quick scan of the manual of django-simple-history).

>  then let's just do that

So not being able to go back to previous versions wouldn't be a problem?

Also, curious for your opinion @vanlummelhuizen .

**Comment by henrinie** [comment] 2019-07-10 09:25
I think django-revision already does what you want, it stores the objects
in json. The problem is to load them to the models in django admin. If you
dont always need the ability to revert changes, it works well for the
recent ones in which the model had no migrations.

I think I made a poor mans version history for glosses based on the json,
it shows what changed in the json compared to the previous version of the
object.

ke 10. heinäk. 2019 klo 11.14 Wessel Stoop <notifications@github.com>
kirjoitti:

**Comment by vanlummelhuizen** [comment] 2019-07-10 10:27
So far my experience with django-simple-history are good. The project seems alive and well maintained. It does not need extra maintenance, as building something our selves would need. 

One of the downsides of starting to use django-simple-history would be the same for something we build: starting a new (versioning) history while we already have one. 

What to do with the old one? Keep using, stop or remove altogether?

**Comment by susanodd** [comment] 2019-07-10 10:52
Can they live next to each other?

**Comment by susanodd** [comment] 2019-07-10 10:56
There could also arise peculiar things since dataset managers can hide phonology fields.
Glosses are updated by ajax calls, so only the fields being updated are affected.
Theoretically, you could have different users updating different fields of a gloss at the same time, as long as they can be serialized. (Is this how the transactions work? Or is the entire gloss locked?)

**Comment by Woseseltops** [comment] 2019-07-10 12:30
I discussed with @vanlummelhuizen , and we've decided that we cannot decide which downsides are more important if we do not have 100% clear what the users want. Most importantly, is the revision history so users can go back to an older version, or is it so users can see who did what when? @ocrasborn do you know this, or shall I contact Julie?

**Comment by ocrasborn** [comment] 2019-07-16 08:52
I'll remind Julie to respond to this, sent her a mail some time ago.

**Comment by ocrasborn** [comment] 2019-07-18 18:31
--> Here's Julie's response:
Whenever I think about how a revision history would be good for me, it's mainly in the sense of who did this edit and when? And I usually want to know so I can follow up on the change. Even if it's myself 😂🤷🏻‍♀️

I don't need the option to revert back. It's easy enough to do it manually if need be. "access this via each gloss, getting a full revision history per gloss" - that's what I'm thinking I think. But I will defer to your expertise in what's possible given time and the design constraints of thee system.

**Comment by Woseseltops** [comment] 2019-07-26 10:50
Okay, sounds like we will go for a simple model GlossRevision then. Agreed @vanlummelhuizen ?

Steps to get there:
* Create simple model with foreign key for the gloss, foreign key for the user that made the change, the date, and strings for field name, old value and new value.
* Adjust the update function to create a new gloss revision every time a gloss field is edited. 
* Add a new tab button to the gloss detail view, going to signbank.cls.ru.nl/dictionary/gloss/1234/history
* Create a new page that responds to to this url (view and template).

**Comment by Woseseltops** [comment] 2019-08-23 12:25
I did:

> Create simple model with foreign key for the gloss, foreign key for the user that made the change, the date, and strings for field name, old value and new value.

And made a start with:

> Adjust the update function to create a new gloss revision every time a gloss field is edited.

But I would have to check whether it works for all types of fields.

**Comment by susanodd** [comment] 2019-09-25 09:28
I'll work on checking that all types of fields are being saved.

**Comment by susanodd** [comment] 2019-09-26 07:44
@Woseseltops, I made a new unit test RevisionHistoryTests -> test_field_types  that checks whether all the (non-foreign-keys) types of gloss fields are in the revision history. Yes.

**Comment by Woseseltops** [comment] 2019-10-16 10:49
Okay the revision history page is there! Happy @ocrasborn ?

**Comment by susanodd** [comment] 2019-10-17 14:19
I fixed the new Revision History View so it displays the datasets in the header. And its tab has been hidden in Public View.

**Comment by ocrasborn** [comment] 2019-11-12 15:30
Wonderfull, all!

**Comment by ocrasborn** [comment] 2020-02-04 23:01
And in addition to my comment of Nov. 12 last year: Julie (sitting next to me here in DC) doesn't have access to this yet. Perhaps high time to update the ASL version again?

**Comment by Woseseltops** [comment] 2020-02-26 12:58
Update completed.

**Closed by Woseseltops** 2020-02-26 12:58 UTC
Labels: asl, blocking, enhancement, high priority
