### ISSUE TITLE
User registration / setting dataset access broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#694] opened 2020-11-04 21:01 UTC
Something's broken in the registration and application for dataset access function. I got three requests for NGT dataset access from students, who had just registered, but for whom I did not get a 'activate account' email. I manually activated the accounts in the admin, but then still didn't see their names pop up in the field for setting view access on the Manage Datasets page. In fact, no user name suggestions pop up at all, whatever character I start entering, whether for existing or any of the three new accounts.
I solved this for now by setting dataset object permissions in the admin, but please have a look at this in the coming days.

**Comment by Woseseltops** [comment] 2020-11-06 09:07
If I understand it correctly, there are two separate problems:

1 The email functionality when requesting access for a new dataset does not work
------------------------------------------------------------------------------------------
When I tried to test this, I did not even reach the email stage:

<img src="https://user-images.githubusercontent.com/1909317/98346811-ce73d880-2016-11eb-8434-13450857e80e.png" width=400>

Apparently, the code is mixing up the dataset name and acronyms. I'm guessing this is what happened for the students mentioned by @ocrasborn as well.

2 Searching for users to give access to a dataset returns nothing (manage datasets page)
------------------------------------------------------------------------------------------------
Does that mean that nothing pops up here, @ocrasborn ?

<img src="https://user-images.githubusercontent.com/1909317/98345958-a33cb980-2015-11eb-918b-df0eb60113de.png" width=400>

Because as you can see, for me it does ;).

**Comment by Woseseltops** [comment] 2020-11-06 09:32
Okay, created a fix for problem 1. After that, I receive the email. 

@vanlummelhuizen , I followed our agreement and created a new branch for it. Could you review and merge? Also, I'm unsure if a new branch + review request is needed for every small fix, like this one... perhaps limit it to larger chunks of new functionality?

**Comment by ocrasborn** [comment] 2020-11-06 09:34
@Woseseltops , re: 2:ah, today (?!) I do see lists of users appearing! Well, that problem seems to have gone up in air then. Good!

**Comment by Woseseltops** [comment] 2020-11-06 09:47
Not 100% if it's good ;). If problems go away without us understanding why, they might also come back without us understanding why :P

**Comment by ocrasborn** [comment] 2020-11-06 09:50
Sharp as ever :-)

**Comment by ocrasborn** [comment] 2020-11-06 10:56
Hm, this may well be unrelated, but even after making myself co-owner of dataset with acronym IS_Whynot, I cannot set any access options there on the page. Can do so (and did) in the admin. For any of the other datasets, when I click any of the grant/revoke buttons, the entry fields pop up. But not for IS_Whynot. Why?

**Comment by ocrasborn** [comment] 2020-11-06 12:53
Another observation, possibly related? (If not do move it to a new issue) A new user that I set to 'active' in the admin yesterday, could not see her profile page today. See screen shot of error.
![Error 6-11 profielpagina](https://user-images.githubusercontent.com/10242207/98368347-7d281100-2037-11eb-8378-af633cab95eb.png)

**Comment by vanlummelhuizen** [comment] 2020-11-10 10:57
> @vanlummelhuizen , I followed our agreement and created a new branch for it. Could you review and merge? Also, I'm unsure if a new branch + review request is needed for every small fix, like this one... perhaps limit it to larger chunks of new functionality?

@Woseseltops Your fix could be called a hotfix and I don't think a separate branch and review is necessary for those. My point of suggesting branches and reviewing was that when you e.g. want to make a hotfix you don't want to go through and review many changes on master between the current commit on the live server and HEAD before making that hotfix.

**Comment by vanlummelhuizen** [comment] 2020-11-10 11:59
@Woseseltops I merged your branch with master and put it live. Do you want to delete the branch?

**Comment by Woseseltops** [comment] 2020-11-13 10:21
> but even after making myself co-owner of dataset with acronym IS_Whynot, I cannot set any access options there on the page.

I can reproduce this, seems a separate thing: #695 

> A new user that I set to 'active' in the admin yesterday, could not see her profile page today. See screen shot of error.

What user is this, @ocrasborn ?

> @Woseseltops I merged your branch with master and put it live. Do you want to delete the branch?

Thanks. Maybe only delete when the accompanying issues are closed? @ocrasborn , can you verify problem 1 is also fixed, and if so close the issue?

**Comment by ocrasborn** [comment] 2020-11-26 12:48
@Woseseltops , I'd love to test it, but am hampered by the fact that my test account (testonno) gives the error above upon logging in: "DoesNotExist at...", just like the account for the new user (forgot which that was, sorry)

**Comment by ocrasborn** [comment] 2020-11-27 10:45
OK, the error in my previous message (DoesNotExist at...) goes away if I reload the page (or go back in the browser, I forgot). I then apply for access to dataset EmblemsNL, and as the owner of that dataset, I get a nice email asking me to provide access. So that means that this issue can be closed.

**Closed** 2020-11-27 10:45 UTC
Labels: bug, to be checked by reporter
