### ISSUE TITLE
Put the translations in separate columns per language in Gloss List View

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#580] opened 2019-05-28 13:59 UTC
Make templates more orthogonal w.r.t. dataset languages.
This supplements making column headers not be hard coded in #542.
It also supplements glitches in sorting #539.

**Comment by susanodd** [comment] 2019-05-28 14:28
Here is a screenshot of the separate columns, with generated column headers and ajax gloss rows.
To support redesign of #542 to remove hard coding. The sorting and sorting headers are also generated.

![go-sort-dynamic-header-gloss-list](https://user-images.githubusercontent.com/24272544/58485997-5ccb0600-8165-11e9-80a3-c18935f4a3a6.png)

**Comment by susanodd** [comment] 2019-06-11 12:10
This has been fixed as displayed above as part of Issue #542, for generating based on settings. Because the table header is generated dynamically, it was cleaner to iterate over the keyword language columns.
Iteration and separation of translation languages was also needed for the sorting of columns.
Sorting was broken for keywords. This has been repaired and pushed to github.

**Comment by susanodd** [comment] 2019-06-11 12:11
@ocrasborn can check off on this once live.

**Comment by susanodd** [comment] 2019-06-14 14:21
Some of the issues are finished and awaiting to be put live.

**Comment by vanlummelhuizen** [comment] 2019-06-26 12:36
Changes for this issue are live (for some time already). @susanodd close this?

**Comment by susanodd** [comment] 2019-07-01 09:54
At the demo, @ocrasborn showed that the column values for translations were not appearing under the correct column. He showed this with Japanese.
Indeed, on-line it shows them under the wrong header.
But on my local version, with the newest database, they are correct.
(See screenshots below.)
How is this possible?

Online:
![sort-order-glosses-global](https://user-images.githubusercontent.com/24272544/60427328-c3c15c00-9bf6-11e9-8fa8-fd86b1bd8406.png)

@susanodd's server (with same database):

(Dutch interface)
![column-order-translations-local-nl](https://user-images.githubusercontent.com/24272544/60427352-ce7bf100-9bf6-11e9-8cc6-8eafa5db9ff9.png)

(English interface)
![column-order-translations-local-en](https://user-images.githubusercontent.com/24272544/60427361-db98e000-9bf6-11e9-9362-78da9b1dbb73.png)

**Comment by Woseseltops** [comment] 2019-07-04 10:37
I figured out what was going wrong here: the code that fills a single row (function `glosslist_ajax_complete`) puts the translations in a dictionary:

```python
translations_per_language = {}
for language in dataset_languages:
    translations_per_language[language] = this_gloss.translation_set.filter(language=language)
```

Problem is that dictionaries have no order (unless you would use OrderedDicts), so the order that is actually displayed on the page is not the order in which the languages were provided. I made it a list of tuples, and now the problem is gone:

```python
translations_per_language = []
for language in dataset_languages:
    translations_per_language.append((language,this_gloss.translation_set.filter(language=language)))
```

**Comment by susanodd** [comment] 2019-07-05 15:11
Great @Woseseltops!

**Closed** 2019-07-05 15:11 UTC
