### ISSUE TITLE
Create social media and email buttons in the detail view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#612] opened 2020-02-04 22:57 UTC
...to send the link of a sign to the default mail, Twitter, Facebook clients. Perhaps only in the public view.

**Comment by Woseseltops** [comment] 2020-06-24 12:32
Maybe it make sense to add Open Graph tags to detail view pages first, so they look good when being shared. This is what it looks like to share a public view page on Facebook right now: 

![image](https://user-images.githubusercontent.com/1909317/85556789-7a4bf700-b627-11ea-92c0-e40941403889.png)

**Comment by Woseseltops** [comment] 2020-06-24 13:00
After adding the Open Graph tags:

![image](https://user-images.githubusercontent.com/1909317/85560799-4bd01b00-b62b-11ea-848d-86946ac00c3f.png)

Open Graph tags on many other places, like Twitter:

![image](https://user-images.githubusercontent.com/1909317/85560879-61dddb80-b62b-11ea-9440-b56165337ac3.png)

**Comment by ocrasborn** [comment] 2020-06-25 09:26
Good idea, @Woseseltops . Two requests here:
1. Let's just list the translation equivalents, not the gloss. The concept of a single ID-gloss that also carries meaning keeps confusing people. By showing them the translation equivalents, we capitalise on the effort we've put into creating a more refined view of the semantics. Also, the formulation 'the sign for' suggests too much that there are single word-to-word translations between a spoken and a signed language.
2. I don't think I see the language here, right, in terms of the dataset acronym?
So, let's do this:
Line 1: "<b><i>meaning1, meaning2, meaning3</i> (in dataset_acronym)</b>"
Line 2: <From the dataset_acronym dataset in Global Signbank
Line 3: signbank.cls.ru.nl

**Comment by Woseseltops** [comment] 2020-06-26 08:07
Good point @ocrasborn . What it looks like on Facebook and Twitter right now:

![image](https://user-images.githubusercontent.com/1909317/85834673-12ff8580-b794-11ea-890d-00c7409d9c00.png)
![image](https://user-images.githubusercontent.com/1909317/85834771-3cb8ac80-b794-11ea-8554-fb8a16ad0a5c.png)

Do realize that the we now put the keywords in an OG field called 'title', and the 'from dataset' line in an OG field called 'description', while these things are strictly speaking not a title and a description of the page to URL refers to. It looks good on Twitter and Facebook, but it might look weird on other (future) social media.

**Comment by Woseseltops** [comment] 2020-06-26 08:12
Just for fun, the OG tags also work in WhatsApp:

![image](https://user-images.githubusercontent.com/1909317/85835408-53abce80-b795-11ea-9576-0aca1b780ea0.png)

**Comment by Woseseltops** [comment] 2020-06-26 08:43
Okay the buttons are now there as well. I have used the default Bootstrap ones so they fit in with the rest of Signbank. Unsure yet about position and color.

![image](https://user-images.githubusercontent.com/1909317/85838415-d9ca1400-b799-11ea-9e2f-d008b3a2893c.png)

**Comment by ocrasborn** [comment] 2020-06-26 10:25
I like the subdued grey style in the above screen shot; in my Safari/Mac, they look social blue (bo-ring!).
The links don't give the desired effect yet, though, in my browser: for Facebook, I get the request to paste in a URL.
For Twitter, the URL is there (but I don't dare test yet to see what the result is, don't want it to go viral before we've actually published the NGT dataset, which I've planned for mid July.
Whatsapp: error.
Mail: a link to a png is pasted in my mail-to-be-sent.

**Comment by Woseseltops** [comment] 2020-07-08 09:35
> in my Safari/Mac, they look social blue

Hmm, I can't reproduce this so hard to debug. I've made some chances to the CSS, does this help?

> for Facebook, I get the request to paste in a URL.

Can you screenshot this for me? This is what I get:

![image](https://user-images.githubusercontent.com/1909317/86901451-e7be5400-c10c-11ea-94ee-5f3dde447ab4.png)

> Whatsapp: error.

What error are you getting? Because I have to select a contact, and then it puts the URL in the textbox for that conversation.

> Mail: a link to a png is pasted in my mail-to-be-sent; that link then runs dead.

Ah yes didn't test this properly. It's fixed now.

**Comment by Woseseltops** [comment] 2020-07-10 13:34
Just a crazy idea that popped into my head relating to getting publicity: I could make a mobile friendly page, for example on signbank.cls.ru.nl/gif, where you can search for a sign and get moving/animated results like this:

![image](https://user-images.githubusercontent.com/1909317/87160063-a4a5e180-c2c2-11ea-90a5-b89e2129e033.png)


If you then touch one of these, a gif will be send to WhatsApp so you can send it to others. The meaning and source text  (NGT/Signbank) will be baked into the gif. Would this be a useless gimmick or would (for example) the deaf community enjoy this, @ocrasborn ? I think it would take me only a few hours to make.

**Comment by ocrasborn** [comment] 2022-06-14 11:56
@Woseseltops , that would be great! :-)

**Comment by susanodd** [comment] 2023-06-02 11:23
It looks like the buttons are all there. Except the urls that are shared have http instead of https, and the url for facebook has nothing.

**Comment by susanodd** [comment] 2023-06-07 11:09
I can't find any references in the code.
It looks like Django obtains this using `build_absolute_uri` which seems to get this out of the database.

**Closed** 2023-06-08 10:13 UTC
Labels: enhancement, high priority
