### ISSUE TITLE
Improve solution: incorrect file paths in GlossVideo objects

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#674] opened 2020-07-31 09:18 UTC
Julie reported this error message when trying to upload videos for some glosses:

![image](https://user-images.githubusercontent.com/1909317/89015160-e8669680-d316-11ea-900d-4cf1b4102d7a.png)

I have investigated this issue, and discovered:
* Signbank tries to replace an existing video, but there is no existing video: it is looking for ~DIVORCE-2158.mp4 while the gloss is called DIVORCE (without the tilde), so it should have looked for DIVORCE-2158.mp4 .
* Signbank gets this incorrect information from a GlossVideo object in the database: this is what I get when I search all GlossVideos that belong to this gloss: `<QuerySet [<GlossVideo: glossvideo/~D/~DIVORCE-2158.mp4>, <GlossVideo: glossvideo/DI/DIVORCE-2158.mp4>]>
`
* As the problematic gloss video object is the first one, it never reaches the correct second one.

My first hypothesis was that gloss renaming correctly changes the gloss and the video file, but not the GlossVideo object... but I cannot reproduce this on the ASL Signbank (or the Global Signbank): if I pick a gloss with a video and rename it, I can still upload videos with no problem. My best guess right now is that these incorrect glossvideo objects were created by an older version of the code. What do  you think @vanlummelhuizen ?

I have now solved it by adding this condition `if os.path.isfile(os.path.join(storage.location, self.videofile.name))` to replacing and deleting videos, but this is more like a band aid and not solving the underlying problem. To solve the underlying problem, the main question is whether we expect these incorrect GlossVideo objects will be created again or not. If so, we have to do something to prevent this situation. If not, we can simply add a develop.py tool that removes all glossvideos pointing to non-existing files.

**Comment by Woseseltops** [comment] 2020-08-05 07:42
A Japanese user of the Global Signbank reported this issue, might be the same:

![image](https://user-images.githubusercontent.com/1909317/89385487-fd20a100-d6ff-11ea-8366-dbf9014c2e48.png)

**Comment by susanodd** [comment] 2020-08-06 10:43
I just tried this too.
For this error message:
![image](https://user-images.githubusercontent.com/24272544/89522747-ff5b2c00-d7e1-11ea-87c2-be25e600c1f3.png)

I tried just looking at Gloss 2158.
But this Gloss ID belongs to a different Gloss, DUITSLAND-A.
https://signbank.cls.ru.nl/dictionary/gloss/2158/

**Comment by susanodd** [comment] 2020-08-06 11:29
I tried it on my local server but I can't reproduce the errors.
Of course, I have very few video files already existing.
@Woseseltops , you mentioned the older versions of the code.
We previously adjusted the code to account for special UTF8 characters in file names.
I see the example above has a parentheses in it.
Is it possible there are some invisible characters in some of the filenames?

**Comment by susanodd** [comment] 2020-08-06 11:48
I downloaded one of the videos to my local server and uploaded it (locally) to the gloss to see what the file listing looks like.
It would appear that there are some quote characters in the filenames. Not really sure if those are there or just in the listing.
But I did use a backslash before (N to list the directory.

![ubuntu-listing-glossvideo-TSL](https://user-images.githubusercontent.com/24272544/89528311-19e5d300-d7eb-11ea-8124-03ba0045482f.png)

**Comment by Woseseltops** [comment] 2020-08-07 12:20
> I see the example above has a parentheses in it.
> Is it possible there are some invisible characters in some of the filenames?

I thought about weird chars too, but there also a lot glosses/videos with the same weird chars that do not have the problem.

> It would appear that there are some quote characters in the filenames. 

I think that's just to escape any problems there might be with parentheses.

**Comment by vanlummelhuizen** [comment] 2020-08-17 12:21
I think the assessment that this problem is caused by some code changes is correct. Because there was a wish to put media file in a directory with a dataset acronym as name, I revised the whole GlossVideo file store set up. As a result, some existing GlossVideos and/or media files needed special attention to fit in the new set up. Some GlossVideos and/or files needed to be changed by hand. Perhaps for certain files this was not done properly. @Woseseltops If necessary I can lookup the correction process and apply it again (?) on ASL Signbank. Please let me know.

**Comment by susanodd** [comment] 2020-08-19 08:13
I'm having problems with this too, on my local server. But it's with the unicode characters.

**Comment by vanlummelhuizen** [comment] 2020-08-19 08:33
@susanodd What happens if you set ESCAPE_UPLOADED_VIDEO_FILE_PATH to True in your settings?

**Comment by Woseseltops** [comment] 2020-08-20 08:10
> @Woseseltops If necessary I can lookup the correction process and apply it again (?) on ASL Signbank. Please let me know.

I think it would be good to understand what this correction process did, yes. The goal I want to reach now is to identify GlossVideo objects that have non-existing paths... is this what it does?

**Comment by vanlummelhuizen** [comment] 2020-08-20 08:15
I think so. I hopefully will be able to find it later today. To be continued.

**Comment by vanlummelhuizen** [comment] 2020-08-20 09:22
Take a look at the managment command script signbank/video/management/commands/makeglossvideos.py and run it:

`python bin/develop.py makeglossvideos`

It should fix what is wrong and give you info on what it found. It also tells you when both the original path and new, constructed, path refer to two files. In that case, we should have a look and decide  what to do.

IMPORTANT: make a backup of both  database and files before running. You can  also run the command with --dry-run.

**Comment by susanodd** [comment] 2020-08-20 12:06
The ESCAPE setting didn't help.

**Comment by susanodd** [comment] 2020-09-04 12:55
Okay, I've been commenting on Issue #440 when I should have been commenting on this one.

**Comment by susanodd** [comment] 2020-09-04 13:06
There's a lot of objects in GlossVideo with either "bak.bak" as extension or "bakID" (with ID the GlossVideo ID).
This is causing problems with code that disassembles the filename to grab its extension. Some files are ".mp4" before the .bak.bak. And some have nothing, just the gloss id.
I did a query GlossVideo on "version = 1".
The problem is that when you want to upload a new video, it's querying the already existing (in the database) GlossVideo file (objects).

**Comment by susanodd** [comment] 2020-09-07 10:13
The corresponding dataset ZEI folder for glossimage is missing on the live server.

**Comment by ocrasborn** [comment] 2020-09-07 11:50
@susanodd Ah, so that'll explain also why I didn't see any images for ZEI yet in the interface!

**Comment by susanodd** [comment] 2020-09-14 09:57
There is something weird going on when the filenames are in Farsi.
I have the utf-8 filenames on my local server now.
But I'm still getting problems with the video files (the extracted image, as well as trying to upload an image.)
It looks like Django is reverting the order of things in the path, because of the Right to Left direction.

<Gloss: میوه-A>

glossimage/ZEI/می/میوه-A-37124.png

It's swapped the 2-character folder under the dataset with the gloss.

I suspect that Django is doing something with the Right to Left ordering.
I'm not able to create or retrieve images for the Farci glosses due to whatever Django is doing here.
There aren't any images on the live server.

**Comment by susanodd** [comment] 2021-03-23 10:24
@vanlummelhuizen are you working on this issue?

Is this issue finished?

I have been working on other media file paths (#440 )
That issue has evolved into fixing problems with the paths stored inside OtherMedia objects, because some were referencing the static folder and others didn't have a folder, and still others have weird characters in the path. The code was creating new files with exactly the same filename as the imported file had, thus copying weird characters exactly into an OtherMedia object's path.

@vanlummelhuizen, perhaps you can look at #440 to see the screenshots and contribute.

**Comment by vanlummelhuizen** [comment] 2021-03-24 14:39
@susanodd I am not working on this issue at the moment. I answered some of you question in #440

**Comment by susanodd** [comment] 2023-01-12 11:49
Can this be closed?

**Comment by vanlummelhuizen** [comment] 2023-01-18 14:29
@susanodd Let's close it

**Closed by vanlummelhuizen** 2023-01-18 14:29 UTC
Labels: high priority, asl
